/**
 * External dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { useRef, Fragment, useState, useEffect } from 'react';
import clsx from 'clsx';
import { Button } from '@wordpress/components';
import { find, get, noop } from 'lodash';
// import { withInstanceId } from '@wordpress/compose';
// import { Icon, chevronUp, chevronDown } from '@wordpress/icons';
// import deprecated from '@wordpress/deprecated';

/**
 * Internal dependencies
 */
export type QueryProps = {
    orderby?: string;
    order?: string;
    page?: string;
    per_page?: number;
    /**
     * Allowing string for backward compatibility
     */
    paged?: number | string;
};

export type TableHeader = {
    /**
     * Boolean, true if this column is the default for sorting. Only one column should have this set.
     */
    defaultSort?: boolean;
    /**
     * String, asc|desc if this column is the default for sorting. Only one column should have this set.
     */
    defaultOrder?: string;
    /**
     * Boolean, true if this column should be aligned to the left.
     */
    isLeftAligned?: boolean;
    /**
     * Boolean, true if this column is a number value.
     */
    isNumeric?: boolean;
    /**
     * Boolean, true if this column is sortable.
     */
    isSortable?: boolean;
    /**
     * The API parameter name for this column, passed to `orderby` when sorting via API.
     */
    key: string;
    /**
     * The display label for this column.
     */
    label?: React.ReactNode;
    /**
     * Boolean, true if this column should always display in the table (not shown in toggle-able list).
     */
    required?: boolean;
    /**
     * The label used for screen readers for this column.
     */
    screenReaderLabel?: string;
    /**
     * Additional classname for the header cell
     */
    cellClassName?: string;
    /**
     * Boolean value to control visibility of a header
     */
    visible?: boolean;
};

export type TableRow = {
    /**
     * Display value, used for rendering- strings or elements are best here.
     */
    display?: React.ReactNode;
    /**
     * "Real" value used for sorting, and should be a string or number. A column with `false` value will not be sortable.
     */
    value?: string | number | boolean;
};

/**
 * Props shared between TableProps and TableCardProps.
 */
type CommonTableProps = {
    /**
     * The rowKey used for the key value on each row, a function that returns the key.
     * Defaults to index.
     */
    rowKey?: (row: TableRow[], index: number) => number;
    /**
     * Customize the message to show when there are no rows in the table.
     */
    emptyMessage?: string;
    /**
     * The query string represented in object form
     */
    query?: QueryProps;
    /**
     * Which column should be the row header, defaults to the first item (`0`) (but could be set to `1`, if the first col
     * is checkboxes, for example). Set to false to disable row headers.
     */
    rowHeader?: number | false;
    /**
     * An array of column headers (see `Table` props).
     */
    headers?: Array<TableHeader>;
    /**
     * An array of arrays of display/value object pairs (see `Table` props).
     */
    rows?: Array<Array<TableRow>>;
    /**
     * Additional CSS classes.
     */
    className?: string;
    /**
     * A function called when sortable table headers are clicked, gets the `header.key` as argument.
     */
    onSort?: (key: string, direction: string) => void;
};

export type TableProps = CommonTableProps & {
    /** A unique ID for this instance of the component. This is automatically generated by withInstanceId. */
    // instanceId: number | string;
    /**
     * Controls whether this component is hidden from screen readers. Used by the loading state, before there is data to read.
     * Don't use this on real tables unless the table data is loaded elsewhere on the page.
     */
    ariaHidden?: boolean;
    /**
     * A label for the content in this table
     */
    caption?: string;
    /**
     * Additional classnames
     */
    classNames?: string | Record<string, string>;
};

export type TableSummaryProps = {
    // An array of objects with `label` & `value` properties, which display on a single line.
    data: Array<{
        label: string;
        value: boolean | number | string | React.ReactNode;
    }>;
};

export type TableCardProps = CommonTableProps & {
    /**
     * An array of custom React nodes that is placed at the top right corner.
     */
    actions?: Array<React.ReactNode>;
    /**
     * If a search is provided in actions and should reorder actions on mobile.
     */
    hasSearch?: boolean;
    /**
     * Content to be displayed before the table but after the header.
     */
    tablePreface?: React.ReactNode;
    /**
     * A list of IDs, matching to the row list so that ids[ 0 ] contains the object ID for the object displayed in row[ 0 ].
     */
    ids?: Array<number>;
    /**
     * Defines if the table contents are loading.
     * It will display `TablePlaceholder` component instead of `Table` if that's the case.
     */
    isLoading?: boolean;
    /**
     * A function which returns a callback function to update the query string for a given `param`.
     */
    // Allowing any for backward compatibitlity
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    onQueryChange?: (param: string) => (...props: any) => void;
    /**
     * A function which returns a callback function which is called upon the user changing the visibility of columns.
     */
    onColumnsChange?: (showCols: Array<string>, key?: string) => void;
    /**
     * A callback function that is invoked when the current page is changed.
     */
    onPageChange?: (
        newPage: number,
        direction?: 'previous' | 'next' | 'goto'
    ) => void;
    /**
     * The total number of rows to display per page.
     */
    rowsPerPage: number;
    /**
     * Boolean to determine whether or not ellipsis menu is shown.
     */
    showMenu?: boolean;
    /**
     * An array of objects with `label` & `value` properties, which display in a line under the table.
     * Optional, can be left off to show no summary.
     */
    summary?: TableSummaryProps['data'];
    /**
     * The title used in the card header, also used as the caption for the content in this table.
     */
    title: string;
    /**
     * The total number of rows (across all pages).
     */
    totalRows: number;
};


const ASC = 'asc';
const DESC = 'desc';

const getDisplay = (cell: { display?: React.ReactNode }) =>
    cell.display || null;

/**
 * A table component, without the Card wrapper. This is a basic table display, sortable, but no default filtering.
 *
 * Row data should be passed to the component as a list of arrays, where each array is a row in the table.
 * Headers are passed in separately as an array of objects with column-related properties. For example,
 * this data would render the following table.
 *
 * ```js
 * const headers = [ { label: 'Month' }, { label: 'Orders' }, { label: 'Revenue' } ];
 * const rows = [
 * 	[
 * 		{ display: 'January', value: 1 },
 * 		{ display: 10, value: 10 },
 * 		{ display: '$530.00', value: 530 },
 * 	],
 * 	[
 * 		{ display: 'February', value: 2 },
 * 		{ display: 13, value: 13 },
 * 		{ display: '$675.00', value: 675 },
 * 	],
 * 	[
 * 		{ display: 'March', value: 3 },
 * 		{ display: 9, value: 9 },
 * 		{ display: '$460.00', value: 460 },
 * 	],
 * ]
 * ```
 *
 * |   Month  | Orders | Revenue |
 * | ---------|--------|---------|
 * | January  |     10 | $530.00 |
 * | February |     13 | $675.00 |
 * | March    |      9 | $460.00 |
 */

const TableTest: React.FC<TableProps> = ({
    // instanceId,
    headers = [],
    rows = [],
    ariaHidden,
    caption,
    className,
    onSort = (f) => f,
    query = {},
    rowHeader,
    rowKey,
    emptyMessage,
    ...props
}) => {
    const { classNames } = props;
    const [tabIndex, setTabIndex] = useState<number | undefined>(undefined);
    const [isScrollableRight, setIsScrollableRight] = useState(false);
    const [isScrollableLeft, setIsScrollableLeft] = useState(false);

    const container = useRef<HTMLDivElement>(null);

    if (classNames) {
        // deprecated(`Table component's classNames prop`, {
        //     since: '11.1.0',
        //     version: '12.0.0',
        //     alternative: 'className',
        //     plugin: '@woocommerce/components',
        // });
    }

    const classes = clsx('woocommerce-table__table', classNames, className, {
        'is-scrollable-right': isScrollableRight,
        'is-scrollable-left': isScrollableLeft,
    });

    const sortBy = (key: string) => {
        return () => {
            const currentKey =
                query.orderby ||
                get(find(headers, { defaultSort: true }), 'key', false);
            const currentDir =
                query.order ||
                get(find(headers, { key: currentKey }), 'defaultOrder', DESC);
            let dir = DESC;
            if (key === currentKey) {
                dir = DESC === currentDir ? ASC : DESC;
            }
            onSort(key, dir);
        };
    };

    const getRowKey = (row: TableRow[], index: number) => {
        if (rowKey && typeof rowKey === 'function') {
            return rowKey(row, index);
        }
        return index;
    };

    const updateTableShadow = () => {
        const table = container.current;

        if (!table) {
            return;
        }

        // Get current dimensions
        const scrollWidth = table.scrollWidth;
        const offsetWidth = table.offsetWidth;
        const scrollLeft = table.scrollLeft;

        // Check if the table is actually scrollable
        const isTableScrollable = scrollWidth > offsetWidth;

        // If table is not scrollable, remove all scroll indicators
        if (!isTableScrollable) {
            setIsScrollableRight(false);
            setIsScrollableLeft(false);
            // Reset scroll position when table is no longer scrollable
            if (scrollLeft !== 0) {
                table.scrollLeft = 0;
            }
            return;
        }

        // Calculate scroll states
        const scrolledToEnd = scrollWidth - scrollLeft <= offsetWidth;
        const scrolledToStart = scrollLeft === 0;

        // Update scroll indicators based on current state
        setIsScrollableRight(!scrolledToEnd);
        setIsScrollableLeft(!scrolledToStart);
    };

    const sortedBy =
        query.orderby ||
        get(find(headers, { defaultSort: true }), 'key', false);
    const sortDir =
        query.order ||
        get(find(headers, { key: sortedBy }), 'defaultOrder', DESC);
    const hasData = !!rows.length;

    useEffect(() => {
        const scrollWidth = container.current?.scrollWidth;
        const clientWidth = container.current?.clientWidth;

        if (scrollWidth === undefined || clientWidth === undefined) {
            return;
        }

        const scrollable = scrollWidth > clientWidth;
        setTabIndex(scrollable ? 0 : undefined);
        updateTableShadow();

        const handleResize = () => {
            // Use requestAnimationFrame to ensure DOM has updated
            requestAnimationFrame(() => {
                updateTableShadow();
            });
        };

        window.addEventListener('resize', handleResize);

        return () => {
            window.removeEventListener('resize', handleResize);
        };
    }, []);

    useEffect(updateTableShadow, [headers, rows, emptyMessage]);

    return (
        <div
            className={classes}
            ref={container}
            tabIndex={tabIndex}
            aria-hidden={ariaHidden}
            // aria-labelledby={`caption-${instanceId}`}
            role="group"
            onScroll={updateTableShadow}
        >
            <table>
                <caption
                    // id={`caption-${instanceId}`}
                    className="woocommerce-table__caption screen-reader-text"
                >
                    {caption}
                    {tabIndex === 0 && (
                        <small>
                            {__('(scroll to see more)', 'woocommerce')}
                        </small>
                    )}
                </caption>
                <tbody>
                    <tr>
                        {headers.map((header, i) => {
                            const {
                                cellClassName,
                                isLeftAligned,
                                isSortable,
                                isNumeric,
                                key,
                                label,
                                screenReaderLabel,
                            } = header;
                            // const labelId = `header-${instanceId}-${i}`;
                            const labelId = `header{i}`;

                            const thProps: { [key: string]: string } = {
                                className: clsx(
                                    'woocommerce-table__header',
                                    cellClassName,
                                    {
                                        'is-left-aligned':
                                            isLeftAligned || !isNumeric,
                                        'is-sortable': isSortable,
                                        'is-sorted': sortedBy === key,
                                        'is-numeric': isNumeric,
                                    }
                                ),
                            };
                            if (isSortable) {
                                thProps['aria-sort'] = 'none';
                                if (sortedBy === key) {
                                    thProps['aria-sort'] =
                                        sortDir === ASC
                                            ? 'ascending'
                                            : 'descending';
                                }
                            }
                            // We only sort by ascending if the col is already sorted descending
                            const iconLabel =
                                sortedBy === key && sortDir !== ASC
                                    ? sprintf(
                                          /* translators: %s: column label */
                                          __(
                                              'Sort by %s in ascending order',
                                              'woocommerce'
                                          ),
                                          screenReaderLabel || label
                                      )
                                    : sprintf(
                                          /* translators: %s: column label */
                                          __(
                                              'Sort by %s in descending order',
                                              'woocommerce'
                                          ),
                                          screenReaderLabel || label
                                      );

                            const textLabel = (
                                <Fragment>
                                    <span
                                        aria-hidden={Boolean(screenReaderLabel)}
                                    >
                                        {label}
                                    </span>
                                    {screenReaderLabel && (
                                        <span className="screen-reader-text">
                                            {screenReaderLabel}
                                        </span>
                                    )}
                                </Fragment>
                            );

                            return (
                                <th
                                    role="columnheader"
                                    scope="col"
                                    key={header.key || i}
                                    {...thProps}
                                >
                                    {isSortable ? (
                                        <Fragment>
                                            <Button
                                                aria-describedby={labelId}
                                                onClick={
                                                    hasData ? sortBy(key) : noop
                                                }
                                            >
                                                {sortedBy === key &&
                                                sortDir === ASC ? (
                                                    // <Icon icon={chevronUp} />
                                                    <>u</>
                                                ) : (
                                                    // <Icon icon={chevronDown} />
                                                    <>d</>
                                                )}
                                                {textLabel}
                                            </Button>
                                            <span
                                                className="screen-reader-text"
                                                id={labelId}
                                            >
                                                {iconLabel}
                                            </span>
                                        </Fragment>
                                    ) : (
                                        textLabel
                                    )}
                                </th>
                            );
                        })}
                    </tr>
                    {hasData ? (
                        rows.map((row, i) => (
                            <tr key={getRowKey(row, i)}>
                                {row.map((cell, j) => {
                                    const {
                                        cellClassName,
                                        isLeftAligned,
                                        isNumeric,
                                    } = headers[j];
                                    const isHeader = rowHeader === j;
                                    const Cell = isHeader ? 'th' : 'td';
                                    const cellClasses = clsx(
                                        'woocommerce-table__item',
                                        cellClassName,
                                        {
                                            'is-left-aligned':
                                                isLeftAligned || !isNumeric,
                                            'is-numeric': isNumeric,
                                            'is-sorted':
                                                sortedBy === headers[j].key,
                                        }
                                    );
                                    const cellKey =
                                        getRowKey(row, i).toString() + j;
                                    return (
                                        <Cell
                                            scope={isHeader ? 'row' : undefined}
                                            key={cellKey}
                                            className={cellClasses}
                                        >
                                            {getDisplay(cell)}
                                        </Cell>
                                    );
                                })}
                            </tr>
                        ))
                    ) : (
                        <tr>
                            <td
                                className="woocommerce-table__empty-item"
                                colSpan={headers.length}
                            >
                                {emptyMessage ??
                                    __('No data to display', 'woocommerce')}
                            </td>
                        </tr>
                    )}
                </tbody>
            </table>
        </div>
    );
};

// export default withInstanceId(Table);
export default TableTest;