import { ButtonAction } from "./ButtonActions";
import { ActionItem } from "./TableRowActions";

export type FilterValue = string | string[] | { startDate: Date; endDate: Date };

export type QueryProps = {
	orderby?: string;
	order?: string;
	page?: string;
	per_page?: number;
	/**
	 * Allowing string for backward compatibility
	 */
	paged?: number | string;
	filter?: Record<string, FilterValue>;
	categoryFilter?: string;
};

export type CategoryCount = {
	label: string;
	value: string;
	count: number
}

export type TableHeaderConfig = {
	/**
	 * Display label
	 */
	label?: React.ReactNode;

	/**
	 * Sorting
	 */
	isSortable?: boolean;
	defaultSort?: boolean;
	defaultOrder?: 'asc' | 'desc';

	/**
	 * Alignment
	 */
	isNumeric?: boolean;
	isLeftAligned?: boolean;

	/**
	 * Visibility control
	 */
	required?: boolean;
	visible?: boolean;

	/**
	 * Accessibility
	 */
	screenReaderLabel?: string;
	cellClassName?: string;

	/**
	 * Built-in renderer type
	 */
	type?: 'text' | 'currency' | 'date' | 'badge' | 'action';

	/**
	 * Custom renderer (overrides type)
	 */
	render?: (
		row?: {}
	) => React.ReactNode;

	/**
	 * Inline editing
	 */
	isEditable?: boolean;
	editType?: 'text' | 'number' | 'select';

	options?: {
		label: string;
		value: string | number;
	}[];

	/**
	 * Action column config
	 */
	actions?: ActionItem[];
	csvDisplay?: boolean,
	tableDisplay?: boolean,
	width?: string | number,
	className?: string,
};


export type TableRow = {
	id?: string | number;
	[key: string]:
	| string
	| number
	| boolean
	| React.ReactNode
};


/**
 * Props shared between TableProps and TableCardProps.
 */
type CommonTableProps = {
	/**
	 * The query string represented in object form
	 */
	query?: QueryProps;
	/**
	 * An array of column headers (see `Table` props).
	 */
	headers?: Record<string, TableHeaderConfig>;
	/**
	 * An array of arrays of display/value object pairs (see `Table` props).
	 */
	rows?: Array<{}>;
	/**
	 * Additional CSS classes.
	 */
	className?: string;
	/**
	 * A function called when sortable table headers are clicked, gets the `header.key` as argument.
	 */
	onSort?: (key: string, direction: string) => void;
};

export type TableProps = CommonTableProps & {
	/** A unique ID for this instance of the component. This is automatically generated by withInstanceId. */
	// instanceId: number | string;
	/**
	 * A label for the content in this table
	 */
	caption?: string;
	/**
	 * Additional classnames
	 */
	classNames?: string | Record<string, string>;
	ids?: Array<number>;
	selectedIds?: Array<number>;
	onSelectRow?: (id: number, selected: boolean) => void;
	onSelectAll?: (selected: boolean) => void;
	rowActions?: ActionItem[];
	onCellEdit?: (key: string, row: TableRow, value: string | number | boolean) => void;
	isLoading?: boolean;
	enableBulkSelect?: boolean;
	format?: string,
	currency?: {};
};

export type TableSummaryProps = {
	// An array of objects with `label` & `value` properties, which display on a single line.
	data: Array<{
		label: string;
		value: boolean | number | string | React.ReactNode;
	}>;
};

export type TableCardProps = CommonTableProps & {
	/**
	 * A list of IDs, matching to the row list so that ids[ 0 ] contains the object ID for the object displayed in row[ 0 ].
	 */
	ids?: Array<number>;
	/**
	 * Defines if the table contents are loading.
	 * It will display `TablePlaceholder` component instead of `Table` if that's the case.
	 */
	isLoading?: boolean;
	/**
	 * A function which returns a callback function to update the query string for a given `param`.
	 */
	onQueryChange?: (param: string) => (...props: any) => void;
	/**
	 * A function which returns a callback function which is called upon the user changing the visibility of columns.
	 */
	onColumnsChange?: (showCols: Array<string>, key?: string) => void;
	/**
	 * A callback function that is invoked when the current page is changed.
	 */
	onPageChange?: (
		newPage: number,
		direction?: 'previous' | 'next' | 'goto'
	) => void;
	/**
	 * Boolean to determine whether or not ellipsis menu is shown.
	 */
	showMenu?: boolean;
	/**
	 * An array of objects with `label` & `value` properties, which display in a line under the table.
	 * Optional, can be left off to show no summary.
	 */
	summary?: TableSummaryProps['data'];
	/**
	 * The title used in the card header, also used as the caption for the content in this table.
	 */
	title: string;
	/**
	 * The total number of rows (across all pages).
	 */
	totalRows: number;
	bulkActions?: Array<{ label: string; value: string }>;
	onBulkActionApply?: (action: string, selectedIds: number[]) => void;
	search?: {
		placeholder?: string;
		options?: {
			label: string;
			value: string;
		}[];
	};
	onQueryUpdate?: (query: QueryProps) => void;
	filters?: RealtimeFilterConfig[];
	categoryCounts?: categoryCount[];
	activeCategory?: string; // optional
	onCategoryClick?: (value: string) => void;
	showColumnToggleIcon?: boolean;
	rowActions?: ActionItem[];
	onSelectCsvDownloadApply?: (selectedIds: number[]) => void;
	onCellEdit?: (key: string, row: TableRow, value: string | number | boolean) => void;
	buttonActions?: ButtonAction[];
	format?: string;
	currency?: {};
};

export type FilterOption = {
	label: string;
	value: string;
};

export type RealtimeFilterConfig = {
	key: string;
	label: string;
	type: 'select' | 'date';
	multiple?: boolean;
	options?: FilterOption[];
};
