import AutoGeneratedDefaultInput from '../src/components/AutoGeneratedDefaultInput';
import type { Meta, StoryObj } from '@storybook/react';

const meta: Meta< typeof AutoGeneratedDefaultInput > = {
	title: 'Zyra/Components/AutoGeneratedDefaultInput',
	component: AutoGeneratedDefaultInput,
	tags: [ 'autodocs' ],
};

export default meta;

type Story = StoryObj< typeof AutoGeneratedDefaultInput >;

export const TestAutoGeneratedDefaultInputInput: Story = {
	args: {
		value: '',
		proSetting: true,
		description: 'This field is only available in the Pro version.',
		onChange: ( newValue ) => {
			console.log( 'Value changed to:', newValue );
		},
	},
	render: ( args ) => {
		return <AutoGeneratedDefaultInput { ...args } />;
	},
};
