import { __ } from '@wordpress/i18n';

export default {
    id: 'non-compliance',
    priority: 2,
    name: __('Compliance Management', 'mvx-pro'),
    desc: __('Control store access based on verification status. Ensure only compliant stores can operate fully on your marketplace.', 'mvx-pro'),
    icon: 'adminlib-compliance',
    submitUrl: 'settings',
    modal: [

        {
            key: 'store_compliance_management',
            type: 'payment-tabs',
            // label: 'What Must Sellers Complete Before Selling?',
            // settingDescription: __('Check all requirements sellers must finish to activate their store', 'multivendorx'),
            modal: [
                {
                    id: 'seller-verification',
                    icon: "adminlib-seller-verification",
                    label: 'Seller verification',
                    connected: true,
                    disableBtn: true,
                    enableOption: true,
                    desc: 'Verify store identity and business legitimacy',
                    moduleEnabled: 'marketplace-compliance',
                    proSetting: true,
                    formFields: [
                        {
                            key: 'enable_advertisement_in_subscription',
                            type: 'setup',
                            title: 'Identity verification',
                            des: 'Control what dashboard sections and tools are available to active stores.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=identity-verification`,
                        },
                        {
                            key: 'display_advertised_product_on_top',
                            type: 'setup',
                            title: 'Social verification',
                            des: 'Control what dashboard sections and tools are available to active stores.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=identity-verification`,
                        },
                        {
                            key: 'out_of_stock_visibility',
                            type: 'setup',
                            title: 'Email verification',
                            des: 'Control what dashboard sections and tools are available to active stores.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=identity-verification`,
                        },
                        {
                            key: 'required_tasks',
                            type: 'multi-checkbox',
                            label: __('Non-Compliance action', 'multivendorx'),
                            class: 'mvx-toggle-checkbox',
                            options: [
                                {
                                    key: 'block_dashboard_access',
                                    label: __('Block dashboard access', 'multivendorx'),
                                    value: 'block_dashboard_access',
                                    // desc: __('Allow stores to advertise products at no extra cost if included in their subscription plan.', 'multivendorx'),
                                },
                                {
                                    key: 'hide_store_from_view',
                                    label: __('Hide store from view', 'multivendorx'),
                                    value: 'hide_store_from_view',
                                    // desc: __('Display advertised products at the top of catalog pages such as the shop or store page.', 'multivendorx'),
                                },
                                {
                                    key: 'disable_product',
                                    label: __('Disable product upload', 'multivendorx'),
                                    value: 'disable_product',
                                    // desc: __('Hide advertised products that are out of stock. Note: if WooCommerce’s out-of-stock visibility setting is enabled, products will be hidden regardless of this setting.', 'multivendorx'),
                                },
                            ],
                            selectDeselect: true,
                        },
                    ],
                },
                {
                    id: 'product-compliance',
                    icon: "adminlib-product",
                    label: 'Product compliance',
                    disableBtn: true,
                    desc: 'Ensure product listings meet marketplace standards',
                    moduleEnabled: 'marketplace-compliance',
                    proSetting: true,
                    formFields: [
                        {
                            key: 'prohibited_items_check',
                            type: 'setup',
                            title: 'Prohibited items check',
                            des: 'Block restricted or banned products to maintain marketplace compliance.',
                           link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=product-compliance`,
                        },
                        {
                            key: 'product_images_descriptions',
                            type: 'setup',
                            title: 'Product images & descriptions',
                            des: 'Approve product reviews before publishing to ensure quality and consistency.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=product-compliance`,
                        },
                        {
                            key: 'product_authenticity_certificates',
                            type: 'setup',
                            title: 'Product authenticity certificates',
                            des: 'Enforce product image and description standards for authenticity and trust.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=product-compliance`,
                        },
                        {
                            key: 'product_abuse_reporting',
                            type: 'setup',
                            title: 'Product abuse reporting',
                            des: 'Handle product violation or abuse reports effectively to ensure compliance.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=product-compliance`,
                        },
                        {
                            key: 'non_compliance_action',
                            type: 'multi-checkbox',
                            label: __('Non-Compliance action', 'multivendorx'),
                            class: 'mvx-toggle-checkbox',
                            options: [
                                {
                                    key: 'prevent_product_publishing',
                                    label: __('Prevent publishing', 'multivendorx'),
                                    value: 'PreventProductPublishing',
                                    // desc: __('Stop vendors from publishing new products until compliance is restored.', 'multivendorx'),
                                },
                                {
                                    key: 'set_store_as_pending',
                                    label: __('Set store as pending', 'multivendorx'),
                                    value: 'SetStoreAsPending',
                                    // desc: __('Change store status to pending until compliance issues are resolved.', 'multivendorx'),
                                },
                                {
                                    key: 'notify_admin_only',
                                    label: __('Notify admin only', 'multivendorx'),
                                    value: 'NotifyAdmin',
                                    // desc: __('Alert admin about non-compliance without restricting store operations.', 'multivendorx'),
                                },
                            ],
                            selectDeselect: true,
                        },
                    ],
                },
                {
                    id: 'legal-policy',
                    icon: "adminlib-verification3",
                    label: 'Legal & policy',
                    moduleEnabled: 'marketplace-compliance',
                    proSetting: true,
                    disableBtn: true,
                    desc: 'Require acceptance of platform terms and policies',
                    formFields: [
                        {
                            key: 'terms_conditions',
                            type: 'setup',
                            title: 'Terms & Conditions',
                            des: 'Require vendors to accept platform terms and conditions before proceeding.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=legal-compliance`,
                        },
                        {
                            key: 'privacy_policy_consent',
                            type: 'setup',
                            title: 'Privacy policy consent',
                            des: 'Ensure vendors acknowledge and agree to your platform’s data handling policies.',
                           link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=legal-compliance`,
                        },
                        {
                            key: 'seller_agreement_upload',
                            type: 'setup',
                            title: 'Seller agreement upload',
                            des: 'Collect signed seller agreements as part of the onboarding process.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=legal-compliancen`,
                        },
                        {
                            key: 'return_policy_compliance',
                            type: 'setup',
                            title: 'Return policy compliance',
                            des: 'Ensure vendors follow the marketplace’s standard refund and return guidelines.',
                           link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=legal-compliance`,
                        },
                        {
                            key: 'non_compliance_action',
                            type: 'multi-checkbox',
                            label: __('Non-Compliance action', 'multivendorx'),
                            class: 'mvx-toggle-checkbox',
                            options: [
                                {
                                    key: 'block_store_access',
                                    label: __('Block store access', 'multivendorx'),
                                    value: 'BlockStoreAccess',
                                    // desc: __('Prevent vendors from accessing their dashboard until compliance requirements are met.', 'multivendorx'),
                                },
                                {
                                    key: 'restrict_marketplace_features',
                                    label: __('Restrict features', 'multivendorx'),
                                    value: 'RestrictMarketplaceFeatures',
                                    // desc: __('Temporarily disable certain selling features or tools for non-compliant stores.', 'multivendorx'),
                                },
                                {
                                    key: 'notify_admin_only',
                                    label: __('Notify admin only', 'multivendorx'),
                                    value: 'NotifyAdmin',
                                    // desc: __('Alert admin about compliance violations without affecting store access.', 'multivendorx'),
                                },
                            ],
                            selectDeselect: true,
                        },
                    ],
                },
                {
                    id: 'financial-compliance',
                    icon: "adminlib-dollar",
                    label: 'Financial compliance',
                    disableBtn: true,
                    moduleEnabled: 'marketplace-compliance',
                    proSetting: true,
                    // countBtn: true,
                    desc: 'Verify tax information and monitor transactions',
                    formFields: [
                        {
                            key: 'tax_information',
                            type: 'setup',
                            title: 'Tax information',
                            des: 'Require vendors to provide valid TIN, VAT, GST, EIN, or other tax identification details.',
                           link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=tax-compliance`,
                        },
                        {
                            key: 'bank_account_details',
                            type: 'setup',
                            title: 'Bank account details',
                            des: 'Collect verified bank details to ensure secure and accurate payouts.',
                            link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=tax-compliance`,
                        },
                        {
                            key: 'commission_transparency',
                            type: 'setup',
                            title: 'Commission transparency',
                            des: 'Maintain clear visibility of fee deductions and payout transactions.',
                           link: `${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=settings&subtab=tax-compliance`,
                        },
                        {
                            key: 'non_compliance_action',
                            type: 'multi-checkbox',
                            label: __('Non-Compliance action', 'multivendorx'),
                            class: 'mvx-toggle-checkbox',
                            options: [
                                {
                                    key: 'disable_payouts',
                                    label: __('Disable payouts', 'multivendorx'),
                                    value: 'DisablePayouts',
                                    // desc: __('Pause vendor payouts until compliance details are verified.', 'multivendorx'),
                                },
                                {
                                    key: 'notify_admin_only',
                                    label: __('Notify admin only', 'multivendorx'),
                                    value: 'NotifyAdmin',
                                    // desc: __('Alert admin of non-compliance without interrupting vendor operations.', 'multivendorx'),
                                },
                            ],
                            selectDeselect: true,
                        },
                    ],
                }
            ]
        },
    ],
};
