import { __ } from '@wordpress/i18n';
export default {
    category: true,
    tab: "modules",
    description: "Manage marketplace features by enabling or disabling modules. Turning a module on activates its settings and workflows, while turning it off hides them from admin and vendors.",
    modules: [
        { type: 'separator', id: 'marketplace_types', label: 'Marketplace Types' },
        {
            id: 'booking',
            name: __('Booking', 'multivendorx'),
            desc: "Allow customers to reserve appointments, equipment, or services.",
            icon: 'adminlib-booking',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/booking-product', 
            req_pluging: [
                { name: 'WooCommerce Booking', link: 'https://woocommerce.com/products/woocommerce-bookings/' }
            ],
            pro_module: true,
            category: ['marketplace_types', 'product_types'],
        },
        {
            id: 'appointment',
            name: __('Appointments', 'multivendorx'),
            desc: "Dedicated appointment booking functionality.",
            icon: 'adminlib-appointments',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/appointment-product/',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            req_pluging: [{ name: 'WooCommerce Appointment', link: 'https://bookingwp.com/plugins/woocommerce-appointments/' }],
            category: ['marketplace_types', 'product_types'],
        },
        {
            id: 'subscription',
            name: __('Subscription', 'multivendorx'),
            desc: "Offer recurring payment options (weekly, monthly, or yearly).",
            icon: 'adminlib-subscription',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/subscription-product',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            req_pluging: [{ name: 'WooCommerce Subscription', link: 'https://woocommerce.com/products/woocommerce-subscriptions/' }],
            category: ['marketplace_types', 'product_types'],
        },
        {
            id: 'accommodation',
            name: __('Accommodation', 'multivendorx'),
            desc: "Enable customers to book overnight stays in just a few clicks.",
            icon: 'adminlib-accommodation',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/accommodation-product',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            req_pluging: [{ name: 'WooCommerce Booking', link: 'https://woocommerce.com/products/woocommerce-bookings/' }
                , { name: 'WooCommerce Accommodation Booking', link: 'https://woocommerce.com/products/woocommerce-accommodation-bookings/' }],
            category: ['marketplace_types', 'product_types'],
        },
        {
            id: 'bundle',
            name: __('Bundle', 'multivendorx'),
            desc: "Offer product bundles, bulk discounts, or assembled kits.",
            icon: 'adminlib-bundle',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/bundle-product',
            pro_module: true,
            req_pluging: [{ name: 'Product Bundle', link: 'https://woocommerce.com/products/product-bundles/' }],
            category: 'product_types'
        },
        {
            id: 'auction',
            name: __('Auction', 'multivendorx'),
            desc: "Enable an auction-style selling system similar to eBay.",
            icon: 'adminlib-auction',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/auction-product',
            pro_module: true,
            req_pluging: [{ name: 'WooCommerce Simple Auction', link: 'https://codecanyon.net/item/woocommerce-simple-auctions-wordpress-auctions/6811382' }
                , { name: 'YITH WooCommerce Auction', link: 'https://yithemes.com/themes/plugins/yith-woocommerce-auctions/' }],
            category: ['marketplace_types', 'product_types'],
        },
        {
            id: 'rental-pro',
            name: __('Rental Pro', 'multivendorx'),
            desc: "Offer rental or real estate booking services.",
            icon: 'adminlib-rental-pro',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/rental-product',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            req_pluging: [{ name: 'RnB WooCommerce Booking & Rental', link: 'https://codecanyon.net/item/rnb-woocommerce-rental-booking-system/14835145?ref=redqteam' }],
            category: ['marketplace_types', 'product_types'],
        },
        { type: 'separator', id: 'product_types', label: 'Product Types' },
        {
            id: 'simple',
            name: __('Simple', 'multivendorx'),
            desc: "Covers basic products such as physical goods (books, clothing) or digital items (PDFs, music, software).",
            icon: 'adminlib-simple',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/simple-product',
            //settings_link: appLocalizer.site_url,
            pro_module: false,
            category: 'product_types'
        },
        {
            id: 'variable',
            name: __('Variable', 'multivendorx'),
            desc: "A product with variations, like different SKU, price, stock option, etc.",
            icon: 'adminlib-variable',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/variable-product',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            category: 'product_types'
        },
        {
            id: 'external',
            name: __('External', 'multivendorx'),
            desc: "List and describe products on your marketplace but sell them elsewhere.",
            icon: 'adminlib-external',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/external-product/',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            category: 'product_types'
        },
        {
            id: 'grouped',
            name: __('Grouped', 'multivendorx'),
            desc: "A collection of simple, related products that can be purchased individually.",
            icon: 'adminlib-grouped',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/grouped-product',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            category: 'product_types'
        },
        {
            id: 'gift-card',
            name: __('Gift Cards', 'multivendorx'),
            desc: "Sell gift cards to boost sales and attract new customers.",
            icon: 'adminlib-gift-card',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/gift-card/',
            //settings_link: appLocalizer.site_url,
            pro_module: true,
            req_pluging: [{ name: 'YITH WooCommerce Gift Cards', link: 'https://wordpress.org/plugins/yith-woocommerce-gift-cards/' }],
            category: 'product_types'
        },
        { type: 'separator', id: 'store_management', label: 'Store Management' },
        {
            id: 'spmv',
            name: __('Single Product Multiple Vendor', 'multivendorx'),
            desc: "Allows more than one store to sell the same product with their own price and stock.",
            icon: 'adminlib-spmv',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/single-product-multiple-vendors-spmv',
            settings_link: '${appLocalizer.settings_page_url}single-product-multiple-store',
            pro_module: false,
            category: 'store_management'
        },
        {
            id: 'import-export',
            name: __('Import Export Tools', 'multivendorx'),
            desc: "Stores will be able to upload or download product lists in bulk using CSV files.",
            icon: 'adminlib-import-export',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/import-export',
            pro_module: true,
            category: 'store_management'
        },
        {
            id: 'store-policy',
            name: __('Store Policy', 'multivendorx'),
            desc: "Each store publishes its own return, refund, and shipping policies.",
            icon: 'adminlib-store-policy',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/store-policy',
            settings_link: '${appLocalizer.settings_page_url}policy',
            pro_module: false,
            category: 'store_management'
        },
        {
            id: 'follow-store',
            name: __('Follow Store', 'multivendorx'),
            desc: "Customers follow stores to receive updates, offers, and product alerts.",
            icon: 'adminlib-follow-store',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/follow-store',
            pro_module: false,
            category: ['store_management','customer_experience'],
        },
        {
            id: 'store-review',
            name: __('Store Review', 'multivendorx'),
            desc: "Customers leave ratings and written reviews on store pages.",
            icon: 'adminlib-store-review',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/store-review',
            settings_link: '${appLocalizer.settings_page_url}review-management',
            pro_module: false,
            category: ['store_management','customer_experience'],
        },
        {
            id: 'business-hours',
            name: __('Business Hours', 'multivendorx'),
            desc: "Shows store opening and closing times for customers.",
            icon: 'adminlib-business-hours',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/business-hours/',
            pro_module: true,
            category: 'store_management'
        },
        {
            id: 'vacation',
            name: __('Vacation', 'multivendorx'),
            desc: "Temporarily disables sales when a store is closed, with a message shown to customers.",
            icon: 'adminlib-vacation',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/vacation',
            pro_module: true,
            category: 'store_management'
        },
        {
            id: 'staff-manager',
            name: __('Staff Manager', 'multivendorx'),
            desc: "Store owners add staff accounts with role-based access to manage orders, products, or support.",
            icon: 'adminlib-staff-manager',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/staff-manager',
            settings_link: '${appLocalizer.settings_page_url}user-capability',
            pro_module: true,
            category: 'store_management'
        },
        {
            id: 'privacy',
            name: __('Privacy', 'multivendorx'),
            desc: "Hide sensitive store information from customers, including contact details, location, or other specified data.",
            icon: 'adminlib-privacy',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/privacy',
            settings_link: '${appLocalizer.settings_page_url}privacy-settings',
            pro_module: false,
            category: 'store_management'

        },
        { type: 'separator', id: 'payment_management', label: 'Payment Management' },
        // {
        //     id: 'bank-transfer',
        //     name: __('Bank Transfer', 'multivendorx'),
        //     desc: "Manually transfer money directly to the store's bank account.",
        //     icon: 'adminlib-rules',
        //     doc_link: 'https://multivendorx.com/docs/knowledgebase/direct-bank-transfer/',
        //     //settings_link: appLocalizer.site_url,
        //     pro_module: false,
        //     category: 'payment_management'
        // },
        // {
        //     id: 'paypal-masspay',
        //     name: __('PayPal Masspay', 'multivendorx'),
        //     desc: "Schedule payment to multiple stores at the same time.",
        //     icon: 'adminlib-rules',
        //     doc_link: 'https://multivendorx.com/docs/knowledgebase/paypal-masspay/',
        //     //settings_link: appLocalizer.site_url,
        //     pro_module: false,
        //     category: 'payment_management'
        // },
        // {
        //     id: 'paypal-payout',
        //     name: __('PayPal Payout', 'multivendorx'),
        //     desc: "Send payments automatically to multiple vendors as per scheduled",
        //     icon: 'adminlib-rules',
        //     doc_link: 'https://multivendorx.com/docs/knowledgebase/paypal-payout',
        //     //settings_link: admin_url('admin.php?page=mvx#&submenu=payment&name=payment-payout'),
        //     pro_module: false,
        //     category: 'payment_management'
        // },
        {
            id: 'paypal-marketplace',
            name: __('PayPal Marketplace (Real time Split)', 'multivendorx'),
            desc: "Using split payment pay vendors instantly after a completed order",
            icon: 'adminlib-paypal-marketplace',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/paypal-marketplace-real-time-split/',
            //settings_link: admin_url('admin.php?page=wc-settings&tab=checkout&section=mvx_paypal_marketplace'),
            pro_module: true,
            category: 'payment_management'
        },
        // {
        //     id: 'stripe-connect',
        //     name: __('Stripe Connect', 'multivendorx'),
        //     desc: "Connect to vendors stripe account and make hassle-free transfers as scheduled.",
        //     icon: 'adminlib-rules',
        //     doc_link: 'https://multivendorx.com/docs/knowledgebase/stripe-connect',
        //     //settings_link: admin_url('admin.php?page=mvx#&submenu=payment&name=payment-stripe-connect'),
        //     pro_module: false,
        //     category: 'payment_management'
        // },
        {
            id: 'stripe-marketplace',
            name: __('Stripe Marketplace (Real time Split)', 'multivendorx'),
            desc: "Automatically sends a store’s share immediately after a customer order is completed.",
            icon: 'adminlib-stripe-marketplace',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/stripe-marketplace',
            //settings_link: admin_url('admin.php?page=mvx#&submenu=payment&name=payment-stripe-connect'),
            pro_module: true,
            category: 'payment_management'
        },
        {
            id: 'mangopay',
            name: __('Mangopay', 'multivendorx'),
            desc: "Gives the benefit of both realtime split transfer and scheduled distribution",
            icon: 'adminlib-mangopay',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/mangopay',
            //settings_link: admin_url('admin.php?page=mvx-setting-admin'),
            pro_module: true,
            category: 'payment_management'
        },
        {
            id: 'razorpay',
            name: __('Razorpay', 'multivendorx'),
            desc: "For clients looking to pay multiple Indian vendors instantly",
            icon: 'adminlib-razorpay',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/payment/',
            //settings_link: admin_url('admin.php?page=mvx-setting-admin'),
            pro_module: false,
            category: 'payment_management'
        },
        { type: 'separator', id: 'shipping_management', label: 'Shipping Management' },
        {
            id: 'zone-shipping',
            name: __('Zone-Wise Shipping', 'multivendorx'),
            desc: "Stores define shipping availability restricted to specific geographic zones.",
            icon: 'adminlib-zone-shipping',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/shipping-by-zone/',
            settings_link: '${appLocalizer.settings_page_url}shipping',
            pro_module: false,
            category: 'shipping_management'
        },
        {
            id: 'distance-shipping',
            name: __('Distance Shipping', 'multivendorx'),
            desc: "Shipping charges calculated based on distance between store address and delivery location.",
            icon: 'adminlib-distance-shipping',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/distance-shipping',
            settings_link: '${appLocalizer.settings_page_url}shipping',
            pro_module: false,
            category: 'shipping_management'
        },
        {
            id: 'country-shipping',
            name: __('Country-Wise Shipping', 'multivendorx'),
            desc: "Stores decide which countries they ship products to.",
            icon: 'adminlib-country-shipping',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/country-shipping',
            settings_link: '${appLocalizer.settings_page_url}shipping',
            pro_module: false,
            category: 'shipping_management'
        },
        {
            id: 'weight-shipping',
            name: __('Weight Wise Shipping (using Table Rate Shipping)', 'multivendorx'),
            desc: "Shipping cost determined by weight, order value, or product quantity.",
            icon: 'adminlib-weight-shipping',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/weight-shipping',
            settings_link: '${appLocalizer.settings_page_url}shipping',
            pro_module: false,
            req_pluging: [{ name: 'Table Rate Shipping', link: 'https://woocommerce.com/products/table-rate-shipping/' }],
            category: 'shipping_management'
        },
        {
            id: 'per-product-shipping',
            name: __('Per Product Shipping', 'multivendorx'),
            desc: "Custom shipping charge applied to individual products.",
            icon: 'adminlib-per-product-shipping',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/per-product-shipping',
            settings_link: '${appLocalizer.settings_page_url}shipping',
            pro_module: true,
            req_pluging: [{ name: 'Per Product Shipping for WooCommerce', link: 'https://woocommerce.com/products/per-product-shipping/' }],
            category: 'shipping_management'
        },
        { type: 'separator', id: 'customer_experience', label: 'Customer Experience' },
        {
            id: 'invoice',
            name: __('Invoice & Packing slip', 'multivendorx'),
            desc: "Generates invoices and packing slips that can be printed or emailed to customers.",
            icon: 'adminlib-invoice',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/invoice-packing-slip',
            settings_link: '${appLocalizer.settings_page_url}store-invoice',
            pro_module: true,
            category: 'customer_experience'
        },
        {
            id: 'live-chat',
            name: __('Live Chat', 'multivendorx'),
            desc: "Customers send real-time messages to stores about products or orders.",
            icon: 'adminlib-live-chat',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/live-chat',
            settings_link: '${appLocalizer.settings_page_url}live-chat',
            pro_module: true,
            category: 'customer_experience'
        },
        {
            id: 'customer-support',
            name: __('Customer Support', 'multivendorx'),
            desc: "Built-in ticketing system for customers to raise and track support requests.",
            icon: 'adminlib-customer-support',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/store-support/',
            settings_link: '${appLocalizer.plugin_url}#&tab=customer-support',
            pro_module: true,
            category: 'customer_experience'
        },
        {
            id: 'question-answer',
            name: __('Question & Answer', 'multivendorx'),
            desc: "Customers can publicly ask product questions.",
            icon: 'adminlib-question-answer',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/shipstation/',
            settings_link: '${appLocalizer.plugin_url}#&tab=customer-support',
            pro_module: false,
            category: 'customer_experience'
        },
        {
            id: 'enquiry',
            name: __('Enquiry', 'multivendorx'),
            desc: "Customers can send private product inquiries.",
            icon: 'adminlib-enquiry',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/shipstation/',
            req_pluging: [{ name: 'CatalogX', link: 'https://catalogx.com/?utm_source=multivendorx&utm_medium=pluginsettings&utm_campaign=multivendorx' }],
            pro_module: true,
            category: 'customer_experience'
        },
        {
            id: 'marketplace-refund',
            name: __('Marketplace Refund', 'multivendorx'),
            desc: "Customers submit refund requests, and stores review and process them directly.",
            icon: 'adminlib-marketplace-refund',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/marketplace-refund',
            settings_link: '${appLocalizer.plugin_url}#&tab=customer-support',
            pro_module: false,
            category: ['store_management','customer_experience'],
        },
        { type: 'separator', id: 'analytics_tools', label: 'Marketing Tools' },
        {
            id: 'store-analytics',
            name: __('Store Analytics', 'multivendorx'),
            desc: "Reports on sales, orders, and revenue, with integration for Google Analytics.",
            icon: 'adminlib-store-analytics',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/store-analytics',
            settings_link: '${appLocalizer.site_url}/wp-admin/admin.php?page=multivendorx#&tab=analytics',
            pro_module: true,
            category: ['analytics_tools','store_management'],
        },
        {
            id: 'store-seo',
            name: __('Store SEO', 'multivendorx'),
            desc: "SEO settings for store pages and products using Rank Math or Yoast SEO.",
            icon: 'adminlib-store-seo',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/store-seo',
            settings_link: '${appLocalizer.settings_page_url}seo',
            pro_module: true,
            category: ['analytics_tools','store_management'],
        },
        { type: 'separator', id: 'marketplace_boosters', label: 'Marketplace Boosters' },
        {
            id: 'marketplace-compliance',
            name: __('Compliance', 'multivendorx'),
            desc: "Ensure stores meet marketplace requirements with automated policy checks.",
            icon: 'adminlib-marketplace-compliance',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/marketplace-memberhsip',
            settings_link: '${appLocalizer.settings_page_url}non-compliance',
            pro_module: true,
            category: 'marketplace_boosters'
        },{
            id: 'marketplace-membership',
            name: __('Marketplace Membership', 'multivendorx'),
            desc: "Admin defines membership levels with specific capabilities for different stores.",
            icon: 'adminlib-marketplace-membership',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/marketplace-memberhsip',
            settings_link: '${appLocalizer.plugin_url}#&tab=memberships&subtab=payment-membership-message',
            pro_module: true,
            category: 'marketplace_boosters'
        },
        {
            id: 'facilitator',
            name: __('Facilitator', 'multivendorx'),
            desc: "Share commission on a sale between the store and another designated user. Each participant receives their assigned portion automatically.",
            icon: 'adminlib-facilitator',
            doc_link: "/admin.php?page=multivendorx#&tab=settings&subtab=store-commissions",
			settings_link: '${appLocalizer.settings_page_url}facilitator',
            pro_module: true,
            category: 'marketplace_boosters'
        },        
        {
            id: 'marketplace-fee',
            name: __('Marketplace Fee', 'multivendorx'),
            desc: "Set and manage platform fees for each order or store to cover operational costs",
            icon: 'adminlib-marketplace-fee',
            doc_link: "/admin.php?page=multivendorx#&tab=settings&subtab=store-commissions",
			settings_link: '${appLocalizer.settings_page_url}store-commissions',
            pro_module: true,
            category: 'marketplace_boosters'
        },
        {
            id: 'marketplace-gateway',
            name: __('Payment Gateway Charge', 'multivendorx'),
            desc: "Payment gateway fees are deducted from vendor commissions by the admin, ensuring platform costs are covered automatically.",
            icon: 'adminlib-marketplace-gateway',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/',
            settings_link: '${appLocalizer.settings_page_url}store-commissions',
            pro_module: false,
            category: ['store_management','payment_management'],
        },
        {
            id: 'advertisement',
            name: __('Advertise Product', 'multivendorx'),
            desc: "Paid promotion for products within the marketplace, boosting visibility.",
            icon: 'adminlib-advertisement',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/advertise-product/',
            settings_link: '${appLocalizer.plugin_url}#&tab=advertisement',
            pro_module: true,
            category: 'marketplace_boosters'
        },
        {
            id: 'wholesale',
            name: __('Wholesale', 'multivendorx'),
            desc: "Stores set wholesale prices and bulk purchase rules for selected customer groups.",
            icon: 'adminlib-wholesale',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/wholesale',
			settings_link: '${appLocalizer.settings_page_url}wholesale',
            pro_module: true,
            category: ['analytics_tools','store_management'],
        },
        {
            id: 'store-inventory',
            name: __('Store Inventory', 'multivendorx'),
            desc: "Manages stock levels, sends low-stock alerts, and maintains a waitlist for out-of-stock products.",
            icon: 'adminlib-store-inventory',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/store-inventory',
            settings_link: '${appLocalizer.settings_page_url}store-inventory',
            pro_module: true,
            category: 'marketplace_boosters'
        },
        {
            id: 'min-max',
            name: __('Min Max Quantities', 'multivendorx'),
            desc: "Defines the minimum or maximum number of items a customer can purchase in a single order.",
            icon: 'adminlib-min-max',
            doc_link: 'https://multivendorx.com/docs/non-knowledgebase/min-max-quantities/',
            settings_link: '${appLocalizer.settings_page_url}min-max',
            pro_module: false,
            category: 'marketplace_boosters'
        },
        { type: 'separator', id: 'notification', label: 'Notification' },
        {
            id: 'announcement',
            name: __('Announcement', 'multivendorx'),
            desc: "Marketplace-wide notices or updates sent from admin to all stores.",
            icon: 'adminlib-announcement',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/announcement/',
            settings_link: '${appLocalizer.plugin_url}#&tab=announcement',
            pro_module: false,
            category: ['notification','marketplace_boosters'],
        },
        {
            id: 'knowladgebase',
            name: __('Knowledgebase', 'multivendorx'),
            desc: "Guides, tutorials, and FAQs shared with stores by the admin.",
            icon: 'adminlib-knowladgebase',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/knowledgebase/',
            settings_link: '${appLocalizer.plugin_url}#&tab=knowledgebase',
            pro_module: false,
            category: 'notification'
        },
        { type: 'separator', id: 'integration', label: 'Integration' },
        {
            id: 'elementor',
            name: __('Elementor', 'multivendorx'),
            desc: "Drag-and-drop design support for custom store pages with Elementor.",
            icon: 'adminlib-elementor',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/mvx-elementor',
            pro_module: false,
            req_pluging: [{ name: 'Elementor Website Builder', link: 'https://wordpress.org/plugins/elementor/' },
            { name: 'Elementor Pro', link: 'https://elementor.com/pricing/' }],
            category: 'integration'
        },
        {
            id: 'buddypress',
            name: __('Buddypress', 'multivendorx'),
            desc: "Adds social networking features to stores (profiles, connections, messaging).",
            icon: 'adminlib-buddypress',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/mvx-buddypress',
            pro_module: false,
            req_pluging: [{ name: 'BuddyPress', link: 'https://wordpress.org/plugins/buddypress/' }],
            category: 'integration'
        },
        {
            id: 'wpml',
            name: __('WPML', 'multivendorx'),
            desc: "Multi-language support so products and stores can be displayed in different languages.",
            icon: 'adminlib-wpml',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/mvx-wpml',
            pro_module: false,
            req_pluging: [{ name: 'WPML', link: 'https://wpml.org/' },
            { name: 'WooCommerce Multilingual', link: 'https://wordpress.org/plugins/woocommerce-multilingual/' }
            ],
            category: 'integration'
        },
        {
            id: 'advance-custom-field',
            name: __('Advance Custom field', 'multivendorx'),
            desc: "Extra custom product fields created by admin for stores to use.",
            icon: 'adminlib-advance-custom-field',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/mvx-acf',
            pro_module: true,
            req_pluging: [{ name: 'Advance Custom Field', link: 'https://wordpress.org/plugins/advanced-custom-fields/' }],
            category: 'integration'
        },
        {
            id: 'geo-my-wp',
            name: __('GEOmyWP', 'multivendorx'),
            desc: "Adds product location data so customers can search by proximity.",
            icon: 'adminlib-geo-my-wp',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/geo-my-wp',
            pro_module: true,
            req_pluging: [{ name: 'GEOmyWP', link: 'https://wordpress.org/plugins/geo-my-wp/' }],
            category: 'integration'
        },
        {
            id: 'wp-affiliate',
            name: __('WP Affiliate', 'multivendorx'),
            desc: "Affiliate program that tracks referrals and commissions for marketplace products.",
            icon: 'adminlib-wp-affiliate',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/affiliate-product/',
            settings_link: '${appLocalizer.settings_page_url}affiliate',
            pro_module: true,
            req_pluging: [{ name: 'Affiliate WP', link: 'https://affiliatewp.com/' }],
            category: 'integration'
        },
        {
            id: 'product-addon',
            name: __('Product Addon', 'multivendorx'),
            desc: "Adds optional extras to products such as gift wrapping, engravings, or warranties.",
            icon: 'adminlib-product-addon',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/mvx-product-addon',
            pro_module: true,
            req_pluging: [{ name: 'Product Addons', link: 'https://woocommerce.com/products/product-add-ons/' }],
            category: 'integration'
        },
        {
            id: 'shipstation-module',
            name: __('Shipstation', 'multivendorx'),
            desc: "Integration with ShipStation for advanced shipping management and label printing.",
            icon: 'adminlib-shipstation-module',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/shipstation/',
            pro_module: true,
            category: ['integration','Shipping management'],    
        },
        {
            id: 'geo-location',
            name: __('Geo Location', 'multivendorx'),
            desc: "Geo Location",
            icon: 'adminlib-geo-location',
            doc_link: 'https://multivendorx.com/docs/knowledgebase/shipstation/',
           settings_link: '${appLocalizer.settings_page_url}geolocation',
            pro_module: false,
            category: 'store_management'
        },
    ]
}
